export function handleError() {
	return { message: 'Internal Error' }; // l'implémetation par défaut de ce hook
}
